name: flutter_medical_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  #Fire Store
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  #email validator
  email_validator: "^2.1.16"
  #string validator
  string_validator: ^1.0.2
  #Phone Number
  phone_number: ^2.0.1
  flutter_svg: ^2.0.5
  intl: ^0.19.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.10
  
  
  
flutter_native_splash:
    color: "#ffffff"
    image: assets/medicalAPP.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/medicalAPP.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
